### PR TITLE
Jmbuzano/gh action ssi

### PR DESCRIPTION
**Pull request by jmbuzano**
## Proposed changes

Adding a job to validate SSI without a matrix strategy, clones and compiles once, validates multiple SSI scenarios.

## Types of changes

What types of changes does your code introduce to the HEBench Frontend?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/hebench/frontend/blob/main/CONTRIBUTING.md) doc
- [x] Current formatting and unit tests / base functionality passes locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did, what alternatives you considered, etc.

### CODE REVIEW

**Review by ajagann — CHANGES_REQUESTED** [review]

**Comment by jmbuzano** [comment]
Per @ajagann advice, I have changed all the actions to use checkout/v3 and $GITHUB_OUTPUT instead of ::set-output.

**Review by ajagann — CHANGES_REQUESTED** [review]
All the shell scripts need an output adjustment in their output when the testcases pass. Need a $0 for the echo statement: https://github.com/hebench/frontend/blob/abf016ce4e6b5bad59ba7c5b6c374be2c77f2f40/.github/validation-ci-ssi/testharness_dsl_PSI_k_smaller_than_biggest_element.sh#L76

**Review by ajagann — APPROVED** [review]
LGTM

**Review by kylanerace — APPROVED** [review]
Nice. This lgtm

**Pull request merged**
