### PR TITLE
linker compatibility

### PR DESCRIPTION
**Pull request by jlakness-intel**
## Proposed changes

linker compatibility on macOS/clang and windows/msvc

## Types of changes

What types of changes does your code introduce to the HEBench Frontend?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/hebench/frontend/blob/main/CONTRIBUTING.md) doc
- [ ] Current formatting and unit tests / base functionality passes locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did, what alternatives you considered, etc.

### CODE REVIEW

**Comment by kylanerace** [comment]
Can we change this to be a PR into hebench:development? Ideally the flow should be as follows:

**Comment by kylanerace** [comment]
Definitely interested in this comment as I believe it's related. Is the failure Apple-specific, or in general to using Clang @jlakness-intel ? (https://github.com/hebench/backend-cpu-cleartext/pull/12#issuecomment-996277320)

**Comment by jlakness-intel** [comment]
> Definitely interested in this ([hebench/backend-cpu-cleartext#12 (comment)](https://github.com/hebench/backend-cpu-cleartext/pull/12#issuecomment-996277320)) comment as I believe it's related. Is the failure Apple-specific, or in general to using Clang @jlakness-intel ? For now approved workflow and updated to run CI.

I was able to build successfully with clang 10.0 on WSL 2.0 Ubuntu. I believe this is a platform-specific difference from GNU ld

**Comment by kylanerace** [comment]
@jlakness-intel Were you able to figure out the issues specific to your Apple setup? If not do we want to go ahead and close this? The PR is pretty stale at this point.

**Comment by kylanerace** [comment]
Closing Stale PR for now (opening when more OS support is added)

**Pull request closed without merging**
